version: '3'
services:
  sa-apollo-proxy: 
    container_name: sa-apollo-proxy
    image: diefrodriguezcha/sa_apollo_proxy
    depends_on:
      - sa-apollo-api
    ports:
      - 80:80
    labels:
      nodo: maps
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: type=rancher-node-maps.c.proyecto-arquisoft.internal
  sa-apollo-api:
    container_name: sa-apollo-api
    image: menoguera/sa_apollo_api
    environment:
      BOT_ENTRY: api/
      BOT_PORT: '3000'
      CENTERS_ENTRY: courses-ms/resources/courses
      CENTERS_PORT: '3001'
      NEWSLETTER_PORT: '3002'
      PORT: '5000'
      SHOW_URLS: 'true'
      URL: '35.190.169.127'
      USER_ENTRY: api/auth
      USER_PORT: '3003'
    labels:
      nodo: maps
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: type=rancher-node-maps.c.proyecto-arquisoft.internal
  sa-user-db:
    container_name: sa-user-db
    image: mongo
    ports:
      - 27018:27018
    labels:
      nodo: maps
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: type=rancher-node-maps.c.proyecto-arquisoft.internal
  sa-news-db:
    container_name: sa-news-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: railsapp
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: appuser
    ports:
      - 3306:3306
    labels:
      nodo: maps
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: type=rancher-node-maps.c.proyecto-arquisoft.internal
  sa-centers-db:
    container_name: sa-centers-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sa-centers-db
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_USER: sa
    ports:
      - 3307:3307
    labels:
      nodo: maps
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: type=rancher-node-maps.c.proyecto-arquisoft.internal
  sa-user-ms:
    container_name: sa-user-ms
    image: diefrodriguezcha/sa_user_ms
    environment:
      DATABASE: '27018'
      DOCKER_DEPLOY: 'true'
      PORT: '3003'
      SECRET: arquisoft
    depends_on:
      - sa-user-db
    links:
      - sa-user-db
    labels:
      nodo: maps
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: type=rancher-node-maps.c.proyecto-arquisoft.internal
  sa-news-ms:
    container_name: sa-news-ms
    image: menoguera/newsletter-api
    environment:
      DB_HOST: sa-news-db
      DB_NAME: railsapp
      DB_PASSWORD: password
      DB_USER: root
    volumes:
      - ./railsapp
    depends_on:
      - sa-news-db
    links:
      - sa-news-db
    labels:
      nodo: maps
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: type=rancher-node-maps.c.proyecto-arquisoft.internal
  sa-centers-ms:
    container_name: sa-centers-ms
    image: dulfrey/sa_centers_ms
    depends_on:
      - sa-centers-db
    links:
      - sa-centers-db
    labels:
      nodo: maps
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: type=rancher-node-maps.c.proyecto-arquisoft.internal