version: '3'
services:
  sa-apollo-proxy: 
    container_name: sa-apollo-proxy
    image: diefrodriguezcha/sa_apollo_proxy
    depends_on:
      - sa-apollo-api
    ports:
      - 80:80
  sa-apollo-api:
    container_name: sa-apollo-api
    image: menoguera/sa_apollo_api:marlon-v
    command: npm serve
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      BOT_ENTRY: 'api/'
      BOT_PORT: '3000'
      CENTERS_URL: 'sa-centers-ms'
      CENTERS_ENTRY: 'courses-ms/resources/courses'
      CENTERS_PORT: '3001'
      NEWSLETTER_URL: 'sa-news-ms'
      NEWSLETTER_PORT: '3002'
      URL: '35.229.96.221'
      USER_URL: 'sa-user-ms'
      USER_ENTRY: 'api/auth'
      USER_PORT: '3003'
  sa-user-db:
    container_name: sa-user-db
    image: mongo
    ports:
      - 27017:27017
  sa-news-db:
    container_name: sa-news-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: railsapp
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: appuser
    ports:
      - 3306:3306
  sa-centers-db:
    container_name: sa-centers-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sa-centers-db
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_USER: sa
    ports:
      - 3307:3307
  sa-user-ms:
    container_name: sa-user-ms
    image: diefrodriguezcha/sa_user_ms
    environment:
      DATABASE: '27017'
      DOCKER_DEPLOY: 'true'
      PORT: '3003'
      SECRET: arquisoft
    depends_on:
      - sa-user-db
    links:
      - sa-user-db
  sa-news-ms:
    container_name: sa-news-ms
    image: menoguera/newsletter-api
    command: bundle exec rails s -p 3002 -b '0.0.0.0'
    environment:
      DB_HOST: sa-news-db
      DB_NAME: railsapp
      DB_PASSWORD: password
      DB_USER: root
      PORT: '3002'
    volumes:
      - ./railsapp
    depends_on:
      - sa-news-db
    links:
      - sa-news-db
  sa-centers-ms:
    container_name: sa-centers-ms
    image: dulfrey/sa_centers_ms
    depends_on:
      - sa-centers-db
    links:
      - sa-centers-db